import './globals.css';
import Link from 'next/link';
import styles from './page.module.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className={styles.navbar}>
          <Link className={styles['nav-item']} href="#">
            Home
          </Link>
          <Link className={styles['nav-item']} href="./about">
            About me
          </Link>
          <Link className={styles['nav-item']} href="./portfolio">
            Portfolio
          </Link>
        </nav>

        {children}
        <footer>
          <h4 className={styles.footer}>
            Copyright 2023 &#169; Designed by David Dyberg
          </h4>
        </footer>
      </body>
    </html>
  );
}
